### ISSUE TITLE
Error with importing module MarkupSafe==1.0

### ISSUE THREAD

**Issue by nmkmms** [ProjectOpenSea/metadata-api-python#12]
Run both on macOS and Ubuntu, and get the same results.
Get error when entered command **pip install -r requirements.txt**

ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bfzg41ju/markupsafe_be07ac2537f04f1eacbef67b93bd8dd4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bfzg41ju/markupsafe_be07ac2537f04f1eacbef67b93bd8dd4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-905vcjc2
         cwd: /tmp/pip-install-bfzg41ju/markupsafe_be07ac2537f04f1eacbef67b93bd8dd4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bfzg41ju/markupsafe_be07ac2537f04f1eacbef67b93bd8dd4/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/lib/python3.9/site-packages/setuptools/__init__.py)

ERROR: Could not find a version that satisfies the requirement MarkupSafe==1.0
ERROR: No matching distribution found for MarkupSafe==1.0

**Comment by thomas-enxuli** [comment]
I faced the same issue and solved by using python=3.5
